### ISSUE TITLE
Strings as boolean values

### ISSUE THREAD

**Issue by Ivo-Balbaert** [Jai-Community/Jai-Community-Library#2]
In this section https://github.com/Jai-Community/Jai-Community-Library/wiki/Getting-Started#strings-as-boolean-values
is written:

" if str is true, then str has charaters in it. If str is false, str is the empty string."

This should better be:

"If str has characters in it, then the automatic cast to boolean is true. Otherwise if str is an empty string, it is false. "

**Comment by shiMusa** [comment]
Changed. Btw, any member of the beta can become a maintainer of the community library. Just send me (Felix) message on the Discord channel with the preferred github account and I'll send you an invite :)

**Comment by Ivo-Balbaert** [comment]
I would like to, but as of yet I am not in the beta. Would always appreciate a recommendation ;-)
