### ISSUE TITLE
Incorrect information regarding dynamic array reallocation frequency

### ISSUE THREAD

**Issue by khisr0w** [Jai-Community/Jai-Community-Library#9]
In the array section of "Getting Started", it is mentioned that:
`The above example works just fine, but involves 50 individual reallocations for no reason, since we already knew we were going to add 50 items. `
Referring to a for loop `1..50` of `array_add(arr, value)`.
This statement is incorrect, since in the current version of the compiler `beta 0.1.092` there will only be 4 allocation for this routine, as shown below:
Size after each allocation: `0 -> 8 -> 16 -> 32 -> 64`

**Comment by danieltan1517** [comment]
Thanks! This has been fixed.
